# Generated by Django 4.2.3 on 2023-08-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('director', models.CharField(max_length=20)),
                ('main_actors', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(default=0)),
            ],
        ),
    ]
