# Generated by Django 4.2.3 on 2023-08-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_tile_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='flyer',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
